version: '3'

services:
  zookeeper1:
    image: wurstmeister/zookeeper:latest
    hostname: zk3
    container_name: zk3
    extra_hosts:
      - "zk1:128.199.105.69"
      - "zk2:128.199.105.69"
    ports:
      - "2183:2183"

    environment:
      zk_id: 3
      ZOOKEEPER_CLIENT_PORT: 2183
  
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 128.199.105.69
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://128.199.105.69:9093
      KAFKA_ZOOKEEPER_CONNECT: 128.199.105.69:2181, 128.199.105.69:2182, 128.199.105.69:2183
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
